@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "jecee",
  "password": "obrero"
}


### Token verification
GET {{host}}/verify-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImplY2VlIiwiaWQiOjEwMCwiZXhwIjoxNjUzODMwMDY4fQ.sMNxu8dIg-YlcBzyqjfo7Hzdu2UQgRSZ3ssq7_OI1k0 HTTP/1.1

