@host = http://127.0.0.1:6000/v1/cats

GET {{host}}/ HTTP/1.1


###
POST {{host}}/ HTTP/1.1
Content-Type: application/json

[
{
    "id": 0,
    "name": "Miming"
},
{
    "id": 1,
    "name": "Mimi"
}
]

###
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Chuckyy"
}


###
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[0,1]



###
GET {{host}}/15 HTTP/1.1


###
PUT {{host}}/15 HTTP/1.1
Content-Type: application/json

{
  "id": 15, 
  "name": "Mimingers"
}


###
DELETE {{host}}/15 HTTP/1.1
